camera_1:
 ros__parameters:
    __ns: "c1"
    video_device: "/dev/video10"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera1"
    pixel_format: "raw_mjpeg"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 1600
    image_height: 1200
    camera_name: "small_camera_1"
    camera_info_url: "package://robot_bringup/config/camera1.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1

camera_2:
 ros__parameters:
    __ns: "c2"
    video_device: "/dev/video8"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera2"
    pixel_format: "raw_mjpeg"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 1600
    image_height: 1200
    camera_name: "small_camera_2"
    camera_info_url: "package://robot_bringup/config/camera2.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1


camera_3:
 ros__parameters:
    __ns: "c3"
    video_device: "/dev/video4"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera3"
    pixel_format: "raw_mjpeg"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 1600
    image_height: 1200
    camera_name: "small_camera_3"
    camera_info_url: "package://robot_bringup/config/camera3.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1

camera_4:
 ros__parameters:
    __ns: "c4"
    video_device: "/dev/video6"
    framerate: 10.0
    io_method: "mmap"
    frame_id: "camera4"
    pixel_format: "raw_mjpeg"  # see usb_cam/supported_formats for list of supported formats
    av_device_format: "YUV422P"
    image_width: 1600
    image_height: 1200
    camera_name: "small_camera_4"
    camera_info_url: "package://robot_bringup/config/camera4.yaml"
    brightness: -1
    contrast: -1
    saturation: -1
    sharpness: -1
    gain: -1
